#!/bin/bash
#
# Regenerates the test fixtures that are derived from ds:commands output and
# drift out of sync whenever commands.sh gains, loses, or renames a command
# (most recently: ds:move, ds:copy, ds:kill_port). Run this after such a
# change and commit the resulting diffs.
#
# Covers:
#   - support/commands                          (the live ds:commands cache)
#   - tests/data/commands                        (golden copy compared in t_basic.sh)
#   - tests/data/commands_shrink_fit_gridlines    (golden ds:fit output, compared in t_fit.sh)
#
# NOT covered: tests/t_reorder.sh has three hardcoded `expected=` blocks
# built by slicing live ds:commands output directly in the test script
# (not file-backed), so they can't be regenerated by copying a fixture.
# This script prints their current values at the end for manual pasting.

set -e

cd "${BASH_SOURCE%/*}/.."
source commands.sh

echo "Regenerating support/commands..."
ds:commands "" "" 1 > /dev/null

echo "Syncing tests/data/commands from support/commands..."
cp support/commands tests/data/commands

echo "Regenerating tests/data/commands_shrink_fit_gridlines..."
ds:fit tests/data/commands -v gridlines=1 -v color=never -v tty_size=120 \
    | sed -E 's/[[:space:]]+$//g' > tests/data/commands_shrink_fit_gridlines

echo
echo "Done. Review before committing:"
echo "  git diff --stat support/commands tests/data/commands tests/data/commands_shrink_fit_gridlines"
echo
echo "tests/t_reorder.sh also has 3 hardcoded 'expected=' blocks built from live"
echo "ds:commands output that this script can't rewrite in place. Current values"
echo "for manual pasting if they've drifted:"

echo
echo "--- len()>130 (line ~81) ---"
ds:commands | grep 'ds:' | ds:reo 'len()>130' off

echo
echo "--- len(4)>46 (line ~87) ---"
ds:commands | grep 'ds:' | ds:reo 'len(4)>46' 2

echo
echo "--- len(2)%11 || len(2)=13 (line ~94) ---"
ds:commands | grep 'ds:' | ds:reo 'len(2)%11 || len(2)=13' 'length()<5 && len()>2'
