#!/usr/bin/sed -f
s/&amp;/\&/g
s/&AElig;/\Æ/g
s/&AMP;/\&/g
s/&Aacute;/\Á/g
s/&Abreve;/\Ă/g
s/&Acirc;/\Â/g
s/&Acy;/\А/g
s/&Afr;/\𝔄/g
s/&Agrave;/\À/g
s/&Alpha;/\Α/g
s/&Amacr;/\Ā/g
s/&And;/\⩓/g
s/&Aogon;/\Ą/g
s/&Aopf;/\𝔸/g
s/&ApplyFunction;/\⁡/g
s/&Aring;/\Å/g
s/&Ascr;/\𝒜/g
s/&Assign;/\≔/g
s/&Atilde;/\Ã/g
s/&Auml;/\Ä/g
s/&Backslash;/\∖/g
s/&Barv;/\⫧/g
s/&Barwed;/\⌆/g
s/&Bcy;/\Б/g
s/&Because;/\∵/g
s/&Bernoullis;/\ℬ/g
s/&Beta;/\Β/g
s/&Bfr;/\𝔅/g
s/&Bopf;/\𝔹/g
s/&Breve;/\˘/g
s/&Bscr;/\ℬ/g
s/&Bumpeq;/\≎/g
s/&CHcy;/\Ч/g
s/&COPY;/\©/g
s/&Cacute;/\Ć/g
s/&Cap;/\⋒/g
s/&CapitalDifferentialD;/\ⅅ/g
s/&Cayleys;/\ℭ/g
s/&Ccaron;/\Č/g
s/&Ccedil;/\Ç/g
s/&Ccirc;/\Ĉ/g
s/&Cconint;/\∰/g
s/&Cdot;/\Ċ/g
s/&Cedilla;/\¸/g
s/&CenterDot;/\·/g
s/&Cfr;/\ℭ/g
s/&Chi;/\Χ/g
s/&CircleDot;/\⊙/g
s/&CircleMinus;/\⊖/g
s/&CirclePlus;/\⊕/g
s/&CircleTimes;/\⊗/g
s/&ClockwiseContourIntegral;/\∲/g
s/&CloseCurlyDoubleQuote;/\”/g
s/&CloseCurlyQuote;/\’/g
s/&Colon;/\∷/g
s/&Colone;/\⩴/g
s/&Congruent;/\≡/g
s/&Conint;/\∯/g
s/&ContourIntegral;/\∮/g
s/&Copf;/\ℂ/g
s/&Coproduct;/\∐/g
s/&CounterClockwiseContourIntegral;/\∳/g
s/&Cross;/\⨯/g
s/&Cscr;/\𝒞/g
s/&Cup;/\⋓/g
s/&CupCap;/\≍/g
s/&DD;/\ⅅ/g
s/&DDotrahd;/\⤑/g
s/&DJcy;/\Ђ/g
s/&DScy;/\Ѕ/g
s/&DZcy;/\Џ/g
s/&Dagger;/\‡/g
s/&Darr;/\↡/g
s/&Dashv;/\⫤/g
s/&Dcaron;/\Ď/g
s/&Dcy;/\Д/g
s/&Del;/\∇/g
s/&Delta;/\Δ/g
s/&Dfr;/\𝔇/g
s/&DiacriticalAcute;/\´/g
s/&DiacriticalDot;/\˙/g
s/&DiacriticalDoubleAcute;/\˝/g
s/&DiacriticalGrave;/\`/g
s/&DiacriticalTilde;/\˜/g
s/&Diamond;/\⋄/g
s/&DifferentialD;/\ⅆ/g
s/&Dopf;/\𝔻/g
s/&Dot;/\¨/g
s/&DotDot;/\⃜/g
s/&DotEqual;/\≐/g
s/&DoubleContourIntegral;/\∯/g
s/&DoubleDot;/\¨/g
s/&DoubleDownArrow;/\⇓/g
s/&DoubleLeftArrow;/\⇐/g
s/&DoubleLeftRightArrow;/\⇔/g
s/&DoubleLeftTee;/\⫤/g
s/&DoubleLongLeftArrow;/\⟸/g
s/&DoubleLongLeftRightArrow;/\⟺/g
s/&DoubleLongRightArrow;/\⟹/g
s/&DoubleRightArrow;/\⇒/g
s/&DoubleRightTee;/\⊨/g
s/&DoubleUpArrow;/\⇑/g
s/&DoubleUpDownArrow;/\⇕/g
s/&DoubleVerticalBar;/\∥/g
s/&DownArrow;/\↓/g
s/&DownArrowBar;/\⤓/g
s/&DownArrowUpArrow;/\⇵/g
s/&DownBreve;/\̑/g
s/&DownLeftRightVector;/\⥐/g
s/&DownLeftTeeVector;/\⥞/g
s/&DownLeftVector;/\↽/g
s/&DownLeftVectorBar;/\⥖/g
s/&DownRightTeeVector;/\⥟/g
s/&DownRightVector;/\⇁/g
s/&DownRightVectorBar;/\⥗/g
s/&DownTee;/\⊤/g
s/&DownTeeArrow;/\↧/g
s/&Downarrow;/\⇓/g
s/&Dscr;/\𝒟/g
s/&Dstrok;/\Đ/g
s/&ENG;/\Ŋ/g
s/&ETH;/\Ð/g
s/&Eacute;/\É/g
s/&Ecaron;/\Ě/g
s/&Ecirc;/\Ê/g
s/&Ecy;/\Э/g
s/&Edot;/\Ė/g
s/&Efr;/\𝔈/g
s/&Egrave;/\È/g
s/&Element;/\∈/g
s/&Emacr;/\Ē/g
s/&EmptySmallSquare;/\◻/g
s/&EmptyVerySmallSquare;/\▫/g
s/&Eogon;/\Ę/g
s/&Eopf;/\𝔼/g
s/&Epsilon;/\Ε/g
s/&Equal;/\⩵/g
s/&EqualTilde;/\≂/g
s/&Equilibrium;/\⇌/g
s/&Escr;/\ℰ/g
s/&Esim;/\⩳/g
s/&Eta;/\Η/g
s/&Euml;/\Ë/g
s/&Exists;/\∃/g
s/&ExponentialE;/\ⅇ/g
s/&Fcy;/\Ф/g
s/&Ffr;/\𝔉/g
s/&FilledSmallSquare;/\◼/g
s/&FilledVerySmallSquare;/\▪/g
s/&Fopf;/\𝔽/g
s/&ForAll;/\∀/g
s/&Fouriertrf;/\ℱ/g
s/&Fscr;/\ℱ/g
s/&GJcy;/\Ѓ/g
s/&GT;/\>/g
s/&Gamma;/\Γ/g
s/&Gammad;/\Ϝ/g
s/&Gbreve;/\Ğ/g
s/&Gcedil;/\Ģ/g
s/&Gcirc;/\Ĝ/g
s/&Gcy;/\Г/g
s/&Gdot;/\Ġ/g
s/&Gfr;/\𝔊/g
s/&Gg;/\⋙/g
s/&Gopf;/\𝔾/g
s/&GreaterEqual;/\≥/g
s/&GreaterEqualLess;/\⋛/g
s/&GreaterFullEqual;/\≧/g
s/&GreaterGreater;/\⪢/g
s/&GreaterLess;/\≷/g
s/&GreaterSlantEqual;/\⩾/g
s/&GreaterTilde;/\≳/g
s/&Gscr;/\𝒢/g
s/&Gt;/\≫/g
s/&HARDcy;/\Ъ/g
s/&Hacek;/\ˇ/g
s/&Hat;/\^/g
s/&Hcirc;/\Ĥ/g
s/&Hfr;/\ℌ/g
s/&HilbertSpace;/\ℋ/g
s/&Hopf;/\ℍ/g
s/&HorizontalLine;/\─/g
s/&Hscr;/\ℋ/g
s/&Hstrok;/\Ħ/g
s/&HumpDownHump;/\≎/g
s/&HumpEqual;/\≏/g
s/&IEcy;/\Е/g
s/&IJlig;/\Ĳ/g
s/&IOcy;/\Ё/g
s/&Iacute;/\Í/g
s/&Icirc;/\Î/g
s/&Icy;/\И/g
s/&Idot;/\İ/g
s/&Ifr;/\ℑ/g
s/&Igrave;/\Ì/g
s/&Im;/\ℑ/g
s/&Imacr;/\Ī/g
s/&ImaginaryI;/\ⅈ/g
s/&Implies;/\⇒/g
s/&Int;/\∬/g
s/&Integral;/\∫/g
s/&Intersection;/\⋂/g
s/&InvisibleComma;/\⁣/g
s/&InvisibleTimes;/\⁢/g
s/&Iogon;/\Į/g
s/&Iopf;/\𝕀/g
s/&Iota;/\Ι/g
s/&Iscr;/\ℐ/g
s/&Itilde;/\Ĩ/g
s/&Iukcy;/\І/g
s/&Iuml;/\Ï/g
s/&Jcirc;/\Ĵ/g
s/&Jcy;/\Й/g
s/&Jfr;/\𝔍/g
s/&Jopf;/\𝕁/g
s/&Jscr;/\𝒥/g
s/&Jsercy;/\Ј/g
s/&Jukcy;/\Є/g
s/&KHcy;/\Х/g
s/&KJcy;/\Ќ/g
s/&Kappa;/\Κ/g
s/&Kcedil;/\Ķ/g
s/&Kcy;/\К/g
s/&Kfr;/\𝔎/g
s/&Kopf;/\𝕂/g
s/&Kscr;/\𝒦/g
s/&LJcy;/\Љ/g
s/&LT;/\</g
s/&Lacute;/\Ĺ/g
s/&Lambda;/\Λ/g
s/&Lang;/\⟪/g
s/&Laplacetrf;/\ℒ/g
s/&Larr;/\↞/g
s/&Lcaron;/\Ľ/g
s/&Lcedil;/\Ļ/g
s/&Lcy;/\Л/g
s/&LeftAngleBracket;/\⟨/g
s/&LeftArrow;/\←/g
s/&LeftArrowBar;/\⇤/g
s/&LeftArrowRightArrow;/\⇆/g
s/&LeftCeiling;/\⌈/g
s/&LeftDoubleBracket;/\⟦/g
s/&LeftDownTeeVector;/\⥡/g
s/&LeftDownVector;/\⇃/g
s/&LeftDownVectorBar;/\⥙/g
s/&LeftFloor;/\⌊/g
s/&LeftRightArrow;/\↔/g
s/&LeftRightVector;/\⥎/g
s/&LeftTee;/\⊣/g
s/&LeftTeeArrow;/\↤/g
s/&LeftTeeVector;/\⥚/g
s/&LeftTriangle;/\⊲/g
s/&LeftTriangleBar;/\⧏/g
s/&LeftTriangleEqual;/\⊴/g
s/&LeftUpDownVector;/\⥑/g
s/&LeftUpTeeVector;/\⥠/g
s/&LeftUpVector;/\↿/g
s/&LeftUpVectorBar;/\⥘/g
s/&LeftVector;/\↼/g
s/&LeftVectorBar;/\⥒/g
s/&Leftarrow;/\⇐/g
s/&Leftrightarrow;/\⇔/g
s/&LessEqualGreater;/\⋚/g
s/&LessFullEqual;/\≦/g
s/&LessGreater;/\≶/g
s/&LessLess;/\⪡/g
s/&LessSlantEqual;/\⩽/g
s/&LessTilde;/\≲/g
s/&Lfr;/\𝔏/g
s/&Ll;/\⋘/g
s/&Lleftarrow;/\⇚/g
s/&Lmidot;/\Ŀ/g
s/&LongLeftArrow;/\⟵/g
s/&LongLeftRightArrow;/\⟷/g
s/&LongRightArrow;/\⟶/g
s/&Longleftarrow;/\⟸/g
s/&Longleftrightarrow;/\⟺/g
s/&Longrightarrow;/\⟹/g
s/&Lopf;/\𝕃/g
s/&LowerLeftArrow;/\↙/g
s/&LowerRightArrow;/\↘/g
s/&Lscr;/\ℒ/g
s/&Lsh;/\↰/g
s/&Lstrok;/\Ł/g
s/&Lt;/\≪/g
s/&Map;/\⤅/g
s/&Mcy;/\М/g
s/&MediumSpace;/\ /g
s/&Mellintrf;/\ℳ/g
s/&Mfr;/\𝔐/g
s/&MinusPlus;/\∓/g
s/&Mopf;/\𝕄/g
s/&Mscr;/\ℳ/g
s/&Mu;/\Μ/g
s/&NJcy;/\Њ/g
s/&Nacute;/\Ń/g
s/&Ncaron;/\Ň/g
s/&Ncedil;/\Ņ/g
s/&Ncy;/\Н/g
s/&NegativeMediumSpace;/\​/g
s/&NegativeThickSpace;/\​/g
s/&NegativeThinSpace;/\​/g
s/&NegativeVeryThinSpace;/\​/g
s/&NestedGreaterGreater;/\≫/g
s/&NestedLessLess;/\≪/g
s/&NewLine;/\ /g
s/&Nfr;/\𝔑/g
s/&NoBreak;/\⁠/g
s/&NonBreakingSpace;/\ /g
s/&Nopf;/\ℕ/g
s/&Not;/\⫬/g
s/&NotCongruent;/\≢/g
s/&NotCupCap;/\≭/g
s/&NotDoubleVerticalBar;/\∦/g
s/&NotElement;/\∉/g
s/&NotEqual;/\≠/g
s/&NotEqualTilde;/\≂̸/g
s/&NotExists;/\∄/g
s/&NotGreater;/\≯/g
s/&NotGreaterEqual;/\≱/g
s/&NotGreaterFullEqual;/\≧̸/g
s/&NotGreaterGreater;/\≫̸/g
s/&NotGreaterLess;/\≹/g
s/&NotGreaterSlantEqual;/\⩾̸/g
s/&NotGreaterTilde;/\≵/g
s/&NotHumpDownHump;/\≎̸/g
s/&NotHumpEqual;/\≏̸/g
s/&NotLeftTriangle;/\⋪/g
s/&NotLeftTriangleBar;/\⧏̸/g
s/&NotLeftTriangleEqual;/\⋬/g
s/&NotLess;/\≮/g
s/&NotLessEqual;/\≰/g
s/&NotLessGreater;/\≸/g
s/&NotLessLess;/\≪̸/g
s/&NotLessSlantEqual;/\⩽̸/g
s/&NotLessTilde;/\≴/g
s/&NotNestedGreaterGreater;/\⪢̸/g
s/&NotNestedLessLess;/\⪡̸/g
s/&NotPrecedes;/\⊀/g
s/&NotPrecedesEqual;/\⪯̸/g
s/&NotPrecedesSlantEqual;/\⋠/g
s/&NotReverseElement;/\∌/g
s/&NotRightTriangle;/\⋫/g
s/&NotRightTriangleBar;/\⧐̸/g
s/&NotRightTriangleEqual;/\⋭/g
s/&NotSquareSubset;/\⊏̸/g
s/&NotSquareSubsetEqual;/\⋢/g
s/&NotSquareSuperset;/\⊐̸/g
s/&NotSquareSupersetEqual;/\⋣/g
s/&NotSubset;/\⊂⃒/g
s/&NotSubsetEqual;/\⊈/g
s/&NotSucceeds;/\⊁/g
s/&NotSucceedsEqual;/\⪰̸/g
s/&NotSucceedsSlantEqual;/\⋡/g
s/&NotSucceedsTilde;/\≿̸/g
s/&NotSuperset;/\⊃⃒/g
s/&NotSupersetEqual;/\⊉/g
s/&NotTilde;/\≁/g
s/&NotTildeEqual;/\≄/g
s/&NotTildeFullEqual;/\≇/g
s/&NotTildeTilde;/\≉/g
s/&NotVerticalBar;/\∤/g
s/&Nscr;/\𝒩/g
s/&Ntilde;/\Ñ/g
s/&Nu;/\Ν/g
s/&OElig;/\Œ/g
s/&Oacute;/\Ó/g
s/&Ocirc;/\Ô/g
s/&Ocy;/\О/g
s/&Odblac;/\Ő/g
s/&Ofr;/\𝔒/g
s/&Ograve;/\Ò/g
s/&Omacr;/\Ō/g
s/&Omega;/\Ω/g
s/&Omicron;/\Ο/g
s/&Oopf;/\𝕆/g
s/&OpenCurlyDoubleQuote;/\“/g
s/&OpenCurlyQuote;/\‘/g
s/&Or;/\⩔/g
s/&Oscr;/\𝒪/g
s/&Oslash;/\Ø/g
s/&Otilde;/\Õ/g
s/&Otimes;/\⨷/g
s/&Ouml;/\Ö/g
s/&OverBar;/\‾/g
s/&OverBrace;/\⏞/g
s/&OverBracket;/\⎴/g
s/&OverParenthesis;/\⏜/g
s/&PartialD;/\∂/g
s/&Pcy;/\П/g
s/&Pfr;/\𝔓/g
s/&Phi;/\Φ/g
s/&Pi;/\Π/g
s/&PlusMinus;/\±/g
s/&Poincareplane;/\ℌ/g
s/&Popf;/\ℙ/g
s/&Pr;/\⪻/g
s/&Precedes;/\≺/g
s/&PrecedesEqual;/\⪯/g
s/&PrecedesSlantEqual;/\≼/g
s/&PrecedesTilde;/\≾/g
s/&Prime;/\″/g
s/&Product;/\∏/g
s/&Proportion;/\∷/g
s/&Proportional;/\∝/g
s/&Pscr;/\𝒫/g
s/&Psi;/\Ψ/g
s/&QUOT;/\"/g
s/&Qfr;/\𝔔/g
s/&Qopf;/\ℚ/g
s/&Qscr;/\𝒬/g
s/&RBarr;/\⤐/g
s/&REG;/\®/g
s/&Racute;/\Ŕ/g
s/&Rang;/\⟫/g
s/&Rarr;/\↠/g
s/&Rarrtl;/\⤖/g
s/&Rcaron;/\Ř/g
s/&Rcedil;/\Ŗ/g
s/&Rcy;/\Р/g
s/&Re;/\ℜ/g
s/&ReverseElement;/\∋/g
s/&ReverseEquilibrium;/\⇋/g
s/&ReverseUpEquilibrium;/\⥯/g
s/&Rfr;/\ℜ/g
s/&Rho;/\Ρ/g
s/&RightAngleBracket;/\⟩/g
s/&RightArrow;/\→/g
s/&RightArrowBar;/\⇥/g
s/&RightArrowLeftArrow;/\⇄/g
s/&RightCeiling;/\⌉/g
s/&RightDoubleBracket;/\⟧/g
s/&RightDownTeeVector;/\⥝/g
s/&RightDownVector;/\⇂/g
s/&RightDownVectorBar;/\⥕/g
s/&RightFloor;/\⌋/g
s/&RightTee;/\⊢/g
s/&RightTeeArrow;/\↦/g
s/&RightTeeVector;/\⥛/g
s/&RightTriangle;/\⊳/g
s/&RightTriangleBar;/\⧐/g
s/&RightTriangleEqual;/\⊵/g
s/&RightUpDownVector;/\⥏/g
s/&RightUpTeeVector;/\⥜/g
s/&RightUpVector;/\↾/g
s/&RightUpVectorBar;/\⥔/g
s/&RightVector;/\⇀/g
s/&RightVectorBar;/\⥓/g
s/&Rightarrow;/\⇒/g
s/&Ropf;/\ℝ/g
s/&RoundImplies;/\⥰/g
s/&Rrightarrow;/\⇛/g
s/&Rscr;/\ℛ/g
s/&Rsh;/\↱/g
s/&RuleDelayed;/\⧴/g
s/&SHCHcy;/\Щ/g
s/&SHcy;/\Ш/g
s/&SOFTcy;/\Ь/g
s/&Sacute;/\Ś/g
s/&Sc;/\⪼/g
s/&Scaron;/\Š/g
s/&Scedil;/\Ş/g
s/&Scirc;/\Ŝ/g
s/&Scy;/\С/g
s/&Sfr;/\𝔖/g
s/&ShortDownArrow;/\↓/g
s/&ShortLeftArrow;/\←/g
s/&ShortRightArrow;/\→/g
s/&ShortUpArrow;/\↑/g
s/&Sigma;/\Σ/g
s/&SmallCircle;/\∘/g
s/&Sopf;/\𝕊/g
s/&Sqrt;/\√/g
s/&Square;/\□/g
s/&SquareIntersection;/\⊓/g
s/&SquareSubset;/\⊏/g
s/&SquareSubsetEqual;/\⊑/g
s/&SquareSuperset;/\⊐/g
s/&SquareSupersetEqual;/\⊒/g
s/&SquareUnion;/\⊔/g
s/&Sscr;/\𝒮/g
s/&Star;/\⋆/g
s/&Sub;/\⋐/g
s/&Subset;/\⋐/g
s/&SubsetEqual;/\⊆/g
s/&Succeeds;/\≻/g
s/&SucceedsEqual;/\⪰/g
s/&SucceedsSlantEqual;/\≽/g
s/&SucceedsTilde;/\≿/g
s/&SuchThat;/\∋/g
s/&Sum;/\∑/g
s/&Sup;/\⋑/g
s/&Superset;/\⊃/g
s/&SupersetEqual;/\⊇/g
s/&Supset;/\⋑/g
s/&THORN;/\Þ/g
s/&TRADE;/\™/g
s/&TSHcy;/\Ћ/g
s/&TScy;/\Ц/g
s/&Tab;/\ /g
s/&Tau;/\Τ/g
s/&Tcaron;/\Ť/g
s/&Tcedil;/\Ţ/g
s/&Tcy;/\Т/g
s/&Tfr;/\𝔗/g
s/&Therefore;/\∴/g
s/&Theta;/\Θ/g
s/&ThickSpace;/\  /g
s/&ThinSpace;/\ /g
s/&Tilde;/\∼/g
s/&TildeEqual;/\≃/g
s/&TildeFullEqual;/\≅/g
s/&TildeTilde;/\≈/g
s/&Topf;/\𝕋/g
s/&TripleDot;/\⃛/g
s/&Tscr;/\𝒯/g
s/&Tstrok;/\Ŧ/g
s/&Uacute;/\Ú/g
s/&Uarr;/\↟/g
s/&Uarrocir;/\⥉/g
s/&Ubrcy;/\Ў/g
s/&Ubreve;/\Ŭ/g
s/&Ucirc;/\Û/g
s/&Ucy;/\У/g
s/&Udblac;/\Ű/g
s/&Ufr;/\𝔘/g
s/&Ugrave;/\Ù/g
s/&Umacr;/\Ū/g
s/&UnderBar;/\_/g
s/&UnderBrace;/\⏟/g
s/&UnderBracket;/\⎵/g
s/&UnderParenthesis;/\⏝/g
s/&Union;/\⋃/g
s/&UnionPlus;/\⊎/g
s/&Uogon;/\Ų/g
s/&Uopf;/\𝕌/g
s/&UpArrow;/\↑/g
s/&UpArrowBar;/\⤒/g
s/&UpArrowDownArrow;/\⇅/g
s/&UpDownArrow;/\↕/g
s/&UpEquilibrium;/\⥮/g
s/&UpTee;/\⊥/g
s/&UpTeeArrow;/\↥/g
s/&Uparrow;/\⇑/g
s/&Updownarrow;/\⇕/g
s/&UpperLeftArrow;/\↖/g
s/&UpperRightArrow;/\↗/g
s/&Upsi;/\ϒ/g
s/&Upsilon;/\Υ/g
s/&Uring;/\Ů/g
s/&Uscr;/\𝒰/g
s/&Utilde;/\Ũ/g
s/&Uuml;/\Ü/g
s/&VDash;/\⊫/g
s/&Vbar;/\⫫/g
s/&Vcy;/\В/g
s/&Vdash;/\⊩/g
s/&Vdashl;/\⫦/g
s/&Vee;/\⋁/g
s/&Verbar;/\‖/g
s/&Vert;/\‖/g
s/&VerticalBar;/\∣/g
s/&VerticalLine;/\|/g
s/&VerticalSeparator;/\❘/g
s/&VerticalTilde;/\≀/g
s/&VeryThinSpace;/\ /g
s/&Vfr;/\𝔙/g
s/&Vopf;/\𝕍/g
s/&Vscr;/\𝒱/g
s/&Vvdash;/\⊪/g
s/&Wcirc;/\Ŵ/g
s/&Wedge;/\⋀/g
s/&Wfr;/\𝔚/g
s/&Wopf;/\𝕎/g
s/&Wscr;/\𝒲/g
s/&Xfr;/\𝔛/g
s/&Xi;/\Ξ/g
s/&Xopf;/\𝕏/g
s/&Xscr;/\𝒳/g
s/&YAcy;/\Я/g
s/&YIcy;/\Ї/g
s/&YUcy;/\Ю/g
s/&Yacute;/\Ý/g
s/&Ycirc;/\Ŷ/g
s/&Ycy;/\Ы/g
s/&Yfr;/\𝔜/g
s/&Yopf;/\𝕐/g
s/&Yscr;/\𝒴/g
s/&Yuml;/\Ÿ/g
s/&ZHcy;/\Ж/g
s/&Zacute;/\Ź/g
s/&Zcaron;/\Ž/g
s/&Zcy;/\З/g
s/&Zdot;/\Ż/g
s/&ZeroWidthSpace;/\​/g
s/&Zeta;/\Ζ/g
s/&Zfr;/\ℨ/g
s/&Zopf;/\ℤ/g
s/&Zscr;/\𝒵/g
s/&aacute;/\á/g
s/&abreve;/\ă/g
s/&ac;/\∾/g
s/&acE;/\∾̳/g
s/&acd;/\∿/g
s/&acirc;/\â/g
s/&acute;/\´/g
s/&acy;/\а/g
s/&aelig;/\æ/g
s/&af;/\⁡/g
s/&afr;/\𝔞/g
s/&agrave;/\à/g
s/&alefsym;/\ℵ/g
s/&aleph;/\ℵ/g
s/&alpha;/\α/g
s/&amacr;/\ā/g
s/&amalg;/\⨿/g
s/&and;/\∧/g
s/&andand;/\⩕/g
s/&andd;/\⩜/g
s/&andslope;/\⩘/g
s/&andv;/\⩚/g
s/&ang;/\∠/g
s/&ange;/\⦤/g
s/&angle;/\∠/g
s/&angmsd;/\∡/g
s/&angmsdaa;/\⦨/g
s/&angmsdab;/\⦩/g
s/&angmsdac;/\⦪/g
s/&angmsdad;/\⦫/g
s/&angmsdae;/\⦬/g
s/&angmsdaf;/\⦭/g
s/&angmsdag;/\⦮/g
s/&angmsdah;/\⦯/g
s/&angrt;/\∟/g
s/&angrtvb;/\⊾/g
s/&angrtvbd;/\⦝/g
s/&angsph;/\∢/g
s/&angst;/\Å/g
s/&angzarr;/\⍼/g
s/&aogon;/\ą/g
s/&aopf;/\𝕒/g
s/&ap;/\≈/g
s/&apE;/\⩰/g
s/&apacir;/\⩯/g
s/&ape;/\≊/g
s/&apid;/\≋/g
s/&apos;/\'/g
s/&approx;/\≈/g
s/&approxeq;/\≊/g
s/&aring;/\å/g
s/&ascr;/\𝒶/g
s/&ast;/\*/g
s/&asymp;/\≈/g
s/&asympeq;/\≍/g
s/&atilde;/\ã/g
s/&auml;/\ä/g
s/&awconint;/\∳/g
s/&awint;/\⨑/g
s/&bNot;/\⫭/g
s/&backcong;/\≌/g
s/&backepsilon;/\϶/g
s/&backprime;/\‵/g
s/&backsim;/\∽/g
s/&backsimeq;/\⋍/g
s/&barvee;/\⊽/g
s/&barwed;/\⌅/g
s/&barwedge;/\⌅/g
s/&bbrk;/\⎵/g
s/&bbrktbrk;/\⎶/g
s/&bcong;/\≌/g
s/&bcy;/\б/g
s/&bdquo;/\„/g
s/&becaus;/\∵/g
s/&because;/\∵/g
s/&bemptyv;/\⦰/g
s/&bepsi;/\϶/g
s/&bernou;/\ℬ/g
s/&beta;/\β/g
s/&beth;/\ℶ/g
s/&between;/\≬/g
s/&bfr;/\𝔟/g
s/&bigcap;/\⋂/g
s/&bigcirc;/\◯/g
s/&bigcup;/\⋃/g
s/&bigodot;/\⨀/g
s/&bigoplus;/\⨁/g
s/&bigotimes;/\⨂/g
s/&bigsqcup;/\⨆/g
s/&bigstar;/\★/g
s/&bigtriangledown;/\▽/g
s/&bigtriangleup;/\△/g
s/&biguplus;/\⨄/g
s/&bigvee;/\⋁/g
s/&bigwedge;/\⋀/g
s/&bkarow;/\⤍/g
s/&blacklozenge;/\⧫/g
s/&blacksquare;/\▪/g
s/&blacktriangle;/\▴/g
s/&blacktriangledown;/\▾/g
s/&blacktriangleleft;/\◂/g
s/&blacktriangleright;/\▸/g
s/&blank;/\␣/g
s/&blk12;/\▒/g
s/&blk14;/\░/g
s/&blk34;/\▓/g
s/&block;/\█/g
s/&bne;/\=⃥/g
s/&bnequiv;/\≡⃥/g
s/&bnot;/\⌐/g
s/&bopf;/\𝕓/g
s/&bot;/\⊥/g
s/&bottom;/\⊥/g
s/&bowtie;/\⋈/g
s/&boxDL;/\╗/g
s/&boxDR;/\╔/g
s/&boxDl;/\╖/g
s/&boxDr;/\╓/g
s/&boxH;/\═/g
s/&boxHD;/\╦/g
s/&boxHU;/\╩/g
s/&boxHd;/\╤/g
s/&boxHu;/\╧/g
s/&boxUL;/\╝/g
s/&boxUR;/\╚/g
s/&boxUl;/\╜/g
s/&boxUr;/\╙/g
s/&boxV;/\║/g
s/&boxVH;/\╬/g
s/&boxVL;/\╣/g
s/&boxVR;/\╠/g
s/&boxVh;/\╫/g
s/&boxVl;/\╢/g
s/&boxVr;/\╟/g
s/&boxbox;/\⧉/g
s/&boxdL;/\╕/g
s/&boxdR;/\╒/g
s/&boxdl;/\┐/g
s/&boxdr;/\┌/g
s/&boxh;/\─/g
s/&boxhD;/\╥/g
s/&boxhU;/\╨/g
s/&boxhd;/\┬/g
s/&boxhu;/\┴/g
s/&boxminus;/\⊟/g
s/&boxplus;/\⊞/g
s/&boxtimes;/\⊠/g
s/&boxuL;/\╛/g
s/&boxuR;/\╘/g
s/&boxul;/\┘/g
s/&boxur;/\└/g
s/&boxv;/\│/g
s/&boxvH;/\╪/g
s/&boxvL;/\╡/g
s/&boxvR;/\╞/g
s/&boxvh;/\┼/g
s/&boxvl;/\┤/g
s/&boxvr;/\├/g
s/&bprime;/\‵/g
s/&breve;/\˘/g
s/&brvbar;/\¦/g
s/&bscr;/\𝒷/g
s/&bsemi;/\⁏/g
s/&bsim;/\∽/g
s/&bsime;/\⋍/g
s/&bsol;/\\/g
s/&bsolb;/\⧅/g
s/&bsolhsub;/\⟈/g
s/&bull;/\•/g
s/&bullet;/\•/g
s/&bump;/\≎/g
s/&bumpE;/\⪮/g
s/&bumpe;/\≏/g
s/&bumpeq;/\≏/g
s/&cacute;/\ć/g
s/&cap;/\∩/g
s/&capand;/\⩄/g
s/&capbrcup;/\⩉/g
s/&capcap;/\⩋/g
s/&capcup;/\⩇/g
s/&capdot;/\⩀/g
s/&caps;/\∩︀/g
s/&caret;/\⁁/g
s/&caron;/\ˇ/g
s/&ccaps;/\⩍/g
s/&ccaron;/\č/g
s/&ccedil;/\ç/g
s/&ccirc;/\ĉ/g
s/&ccups;/\⩌/g
s/&ccupssm;/\⩐/g
s/&cdot;/\ċ/g
s/&cedil;/\¸/g
s/&cemptyv;/\⦲/g
s/&cent;/\¢/g
s/&centerdot;/\·/g
s/&cfr;/\𝔠/g
s/&chcy;/\ч/g
s/&check;/\✓/g
s/&checkmark;/\✓/g
s/&chi;/\χ/g
s/&cir;/\○/g
s/&cirE;/\⧃/g
s/&circ;/\ˆ/g
s/&circeq;/\≗/g
s/&circlearrowleft;/\↺/g
s/&circlearrowright;/\↻/g
s/&circledR;/\®/g
s/&circledS;/\Ⓢ/g
s/&circledast;/\⊛/g
s/&circledcirc;/\⊚/g
s/&circleddash;/\⊝/g
s/&cire;/\≗/g
s/&cirfnint;/\⨐/g
s/&cirmid;/\⫯/g
s/&cirscir;/\⧂/g
s/&clubs;/\♣/g
s/&clubsuit;/\♣/g
s/&colon;/\:/g
s/&colone;/\≔/g
s/&coloneq;/\≔/g
s/&comma;/\,/g
s/&commat;/\@/g
s/&comp;/\∁/g
s/&compfn;/\∘/g
s/&complement;/\∁/g
s/&complexes;/\ℂ/g
s/&cong;/\≅/g
s/&congdot;/\⩭/g
s/&conint;/\∮/g
s/&copf;/\𝕔/g
s/&coprod;/\∐/g
s/&copy;/\©/g
s/&copysr;/\℗/g
s/&crarr;/\↵/g
s/&cross;/\✗/g
s/&cscr;/\𝒸/g
s/&csub;/\⫏/g
s/&csube;/\⫑/g
s/&csup;/\⫐/g
s/&csupe;/\⫒/g
s/&ctdot;/\⋯/g
s/&cudarrl;/\⤸/g
s/&cudarrr;/\⤵/g
s/&cuepr;/\⋞/g
s/&cuesc;/\⋟/g
s/&cularr;/\↶/g
s/&cularrp;/\⤽/g
s/&cup;/\∪/g
s/&cupbrcap;/\⩈/g
s/&cupcap;/\⩆/g
s/&cupcup;/\⩊/g
s/&cupdot;/\⊍/g
s/&cupor;/\⩅/g
s/&cups;/\∪︀/g
s/&curarr;/\↷/g
s/&curarrm;/\⤼/g
s/&curlyeqprec;/\⋞/g
s/&curlyeqsucc;/\⋟/g
s/&curlyvee;/\⋎/g
s/&curlywedge;/\⋏/g
s/&curren;/\¤/g
s/&curvearrowleft;/\↶/g
s/&curvearrowright;/\↷/g
s/&cuvee;/\⋎/g
s/&cuwed;/\⋏/g
s/&cwconint;/\∲/g
s/&cwint;/\∱/g
s/&cylcty;/\⌭/g
s/&dArr;/\⇓/g
s/&dHar;/\⥥/g
s/&dagger;/\†/g
s/&daleth;/\ℸ/g
s/&darr;/\↓/g
s/&dash;/\‐/g
s/&dashv;/\⊣/g
s/&dbkarow;/\⤏/g
s/&dblac;/\˝/g
s/&dcaron;/\ď/g
s/&dcy;/\д/g
s/&dd;/\ⅆ/g
s/&ddagger;/\‡/g
s/&ddarr;/\⇊/g
s/&ddotseq;/\⩷/g
s/&deg;/\°/g
s/&delta;/\δ/g
s/&demptyv;/\⦱/g
s/&dfisht;/\⥿/g
s/&dfr;/\𝔡/g
s/&dharl;/\⇃/g
s/&dharr;/\⇂/g
s/&diam;/\⋄/g
s/&diamond;/\⋄/g
s/&diamondsuit;/\♦/g
s/&diams;/\♦/g
s/&die;/\¨/g
s/&digamma;/\ϝ/g
s/&disin;/\⋲/g
s/&div;/\÷/g
s/&divide;/\÷/g
s/&divideontimes;/\⋇/g
s/&divonx;/\⋇/g
s/&djcy;/\ђ/g
s/&dlcorn;/\⌞/g
s/&dlcrop;/\⌍/g
s/&dollar;/\$/g
s/&dopf;/\𝕕/g
s/&dot;/\˙/g
s/&doteq;/\≐/g
s/&doteqdot;/\≑/g
s/&dotminus;/\∸/g
s/&dotplus;/\∔/g
s/&dotsquare;/\⊡/g
s/&doublebarwedge;/\⌆/g
s/&downarrow;/\↓/g
s/&downdownarrows;/\⇊/g
s/&downharpoonleft;/\⇃/g
s/&downharpoonright;/\⇂/g
s/&drbkarow;/\⤐/g
s/&drcorn;/\⌟/g
s/&drcrop;/\⌌/g
s/&dscr;/\𝒹/g
s/&dscy;/\ѕ/g
s/&dsol;/\⧶/g
s/&dstrok;/\đ/g
s/&dtdot;/\⋱/g
s/&dtri;/\▿/g
s/&dtrif;/\▾/g
s/&duarr;/\⇵/g
s/&duhar;/\⥯/g
s/&dwangle;/\⦦/g
s/&dzcy;/\џ/g
s/&dzigrarr;/\⟿/g
s/&eDDot;/\⩷/g
s/&eDot;/\≑/g
s/&eacute;/\é/g
s/&easter;/\⩮/g
s/&ecaron;/\ě/g
s/&ecir;/\≖/g
s/&ecirc;/\ê/g
s/&ecolon;/\≕/g
s/&ecy;/\э/g
s/&edot;/\ė/g
s/&ee;/\ⅇ/g
s/&efDot;/\≒/g
s/&efr;/\𝔢/g
s/&eg;/\⪚/g
s/&egrave;/\è/g
s/&egs;/\⪖/g
s/&egsdot;/\⪘/g
s/&el;/\⪙/g
s/&elinters;/\⏧/g
s/&ell;/\ℓ/g
s/&els;/\⪕/g
s/&elsdot;/\⪗/g
s/&emacr;/\ē/g
s/&empty;/\∅/g
s/&emptyset;/\∅/g
s/&emptyv;/\∅/g
s/&emsp13;/\ /g
s/&emsp14;/\ /g
s/&emsp;/\ /g
s/&eng;/\ŋ/g
s/&ensp;/\ /g
s/&eogon;/\ę/g
s/&eopf;/\𝕖/g
s/&epar;/\⋕/g
s/&eparsl;/\⧣/g
s/&eplus;/\⩱/g
s/&epsi;/\ε/g
s/&epsilon;/\ε/g
s/&epsiv;/\ϵ/g
s/&eqcirc;/\≖/g
s/&eqcolon;/\≕/g
s/&eqsim;/\≂/g
s/&eqslantgtr;/\⪖/g
s/&eqslantless;/\⪕/g
s/&equals;/\=/g
s/&equest;/\≟/g
s/&equiv;/\≡/g
s/&equivDD;/\⩸/g
s/&eqvparsl;/\⧥/g
s/&erDot;/\≓/g
s/&erarr;/\⥱/g
s/&escr;/\ℯ/g
s/&esdot;/\≐/g
s/&esim;/\≂/g
s/&eta;/\η/g
s/&eth;/\ð/g
s/&euml;/\ë/g
s/&euro;/\€/g
s/&excl;/\!/g
s/&exist;/\∃/g
s/&expectation;/\ℰ/g
s/&exponentiale;/\ⅇ/g
s/&fallingdotseq;/\≒/g
s/&fcy;/\ф/g
s/&female;/\♀/g
s/&ffilig;/\ﬃ/g
s/&fflig;/\ﬀ/g
s/&ffllig;/\ﬄ/g
s/&ffr;/\𝔣/g
s/&filig;/\ﬁ/g
s/&fjlig;/\fj/g
s/&flat;/\♭/g
s/&fllig;/\ﬂ/g
s/&fltns;/\▱/g
s/&fnof;/\ƒ/g
s/&fopf;/\𝕗/g
s/&forall;/\∀/g
s/&fork;/\⋔/g
s/&forkv;/\⫙/g
s/&fpartint;/\⨍/g
s/&frac12;/\½/g
s/&frac13;/\⅓/g
s/&frac14;/\¼/g
s/&frac15;/\⅕/g
s/&frac16;/\⅙/g
s/&frac18;/\⅛/g
s/&frac23;/\⅔/g
s/&frac25;/\⅖/g
s/&frac34;/\¾/g
s/&frac35;/\⅗/g
s/&frac38;/\⅜/g
s/&frac45;/\⅘/g
s/&frac56;/\⅚/g
s/&frac58;/\⅝/g
s/&frac78;/\⅞/g
s/&frasl;/\⁄/g
s/&frown;/\⌢/g
s/&fscr;/\𝒻/g
s/&gE;/\≧/g
s/&gEl;/\⪌/g
s/&gacute;/\ǵ/g
s/&gamma;/\γ/g
s/&gammad;/\ϝ/g
s/&gap;/\⪆/g
s/&gbreve;/\ğ/g
s/&gcirc;/\ĝ/g
s/&gcy;/\г/g
s/&gdot;/\ġ/g
s/&ge;/\≥/g
s/&gel;/\⋛/g
s/&geq;/\≥/g
s/&geqq;/\≧/g
s/&geqslant;/\⩾/g
s/&ges;/\⩾/g
s/&gescc;/\⪩/g
s/&gesdot;/\⪀/g
s/&gesdoto;/\⪂/g
s/&gesdotol;/\⪄/g
s/&gesl;/\⋛︀/g
s/&gesles;/\⪔/g
s/&gfr;/\𝔤/g
s/&gg;/\≫/g
s/&ggg;/\⋙/g
s/&gimel;/\ℷ/g
s/&gjcy;/\ѓ/g
s/&gl;/\≷/g
s/&glE;/\⪒/g
s/&gla;/\⪥/g
s/&glj;/\⪤/g
s/&gnE;/\≩/g
s/&gnap;/\⪊/g
s/&gnapprox;/\⪊/g
s/&gne;/\⪈/g
s/&gneq;/\⪈/g
s/&gneqq;/\≩/g
s/&gnsim;/\⋧/g
s/&gopf;/\𝕘/g
s/&grave;/\`/g
s/&gscr;/\ℊ/g
s/&gsim;/\≳/g
s/&gsime;/\⪎/g
s/&gsiml;/\⪐/g
s/&gt;/\>/g
s/&gtcc;/\⪧/g
s/&gtcir;/\⩺/g
s/&gtdot;/\⋗/g
s/&gtlPar;/\⦕/g
s/&gtquest;/\⩼/g
s/&gtrapprox;/\⪆/g
s/&gtrarr;/\⥸/g
s/&gtrdot;/\⋗/g
s/&gtreqless;/\⋛/g
s/&gtreqqless;/\⪌/g
s/&gtrless;/\≷/g
s/&gtrsim;/\≳/g
s/&gvertneqq;/\≩︀/g
s/&gvnE;/\≩︀/g
s/&hArr;/\⇔/g
s/&hairsp;/\ /g
s/&half;/\½/g
s/&hamilt;/\ℋ/g
s/&hardcy;/\ъ/g
s/&harr;/\↔/g
s/&harrcir;/\⥈/g
s/&harrw;/\↭/g
s/&hbar;/\ℏ/g
s/&hcirc;/\ĥ/g
s/&hearts;/\♥/g
s/&heartsuit;/\♥/g
s/&hellip;/\…/g
s/&hercon;/\⊹/g
s/&hfr;/\𝔥/g
s/&hksearow;/\⤥/g
s/&hkswarow;/\⤦/g
s/&hoarr;/\⇿/g
s/&homtht;/\∻/g
s/&hookleftarrow;/\↩/g
s/&hookrightarrow;/\↪/g
s/&hopf;/\𝕙/g
s/&horbar;/\―/g
s/&hscr;/\𝒽/g
s/&hslash;/\ℏ/g
s/&hstrok;/\ħ/g
s/&hybull;/\⁃/g
s/&hyphen;/\‐/g
s/&iacute;/\í/g
s/&ic;/\⁣/g
s/&icirc;/\î/g
s/&icy;/\и/g
s/&iecy;/\е/g
s/&iexcl;/\¡/g
s/&iff;/\⇔/g
s/&ifr;/\𝔦/g
s/&igrave;/\ì/g
s/&ii;/\ⅈ/g
s/&iiiint;/\⨌/g
s/&iiint;/\∭/g
s/&iinfin;/\⧜/g
s/&iiota;/\℩/g
s/&ijlig;/\ĳ/g
s/&imacr;/\ī/g
s/&image;/\ℑ/g
s/&imagline;/\ℐ/g
s/&imagpart;/\ℑ/g
s/&imath;/\ı/g
s/&imof;/\⊷/g
s/&imped;/\Ƶ/g
s/&in;/\∈/g
s/&incare;/\℅/g
s/&infin;/\∞/g
s/&infintie;/\⧝/g
s/&inodot;/\ı/g
s/&int;/\∫/g
s/&intcal;/\⊺/g
s/&integers;/\ℤ/g
s/&intercal;/\⊺/g
s/&intlarhk;/\⨗/g
s/&intprod;/\⨼/g
s/&iocy;/\ё/g
s/&iogon;/\į/g
s/&iopf;/\𝕚/g
s/&iota;/\ι/g
s/&iprod;/\⨼/g
s/&iquest;/\¿/g
s/&iscr;/\𝒾/g
s/&isin;/\∈/g
s/&isinE;/\⋹/g
s/&isindot;/\⋵/g
s/&isins;/\⋴/g
s/&isinsv;/\⋳/g
s/&isinv;/\∈/g
s/&it;/\⁢/g
s/&itilde;/\ĩ/g
s/&iukcy;/\і/g
s/&iuml;/\ï/g
s/&jcirc;/\ĵ/g
s/&jcy;/\й/g
s/&jfr;/\𝔧/g
s/&jmath;/\ȷ/g
s/&jopf;/\𝕛/g
s/&jscr;/\𝒿/g
s/&jsercy;/\ј/g
s/&jukcy;/\є/g
s/&kappa;/\κ/g
s/&kappav;/\ϰ/g
s/&kcedil;/\ķ/g
s/&kcy;/\к/g
s/&kfr;/\𝔨/g
s/&kgreen;/\ĸ/g
s/&khcy;/\х/g
s/&kjcy;/\ќ/g
s/&kopf;/\𝕜/g
s/&kscr;/\𝓀/g
s/&lAarr;/\⇚/g
s/&lArr;/\⇐/g
s/&lAtail;/\⤛/g
s/&lBarr;/\⤎/g
s/&lE;/\≦/g
s/&lEg;/\⪋/g
s/&lHar;/\⥢/g
s/&lacute;/\ĺ/g
s/&laemptyv;/\⦴/g
s/&lagran;/\ℒ/g
s/&lambda;/\λ/g
s/&lang;/\⟨/g
s/&langd;/\⦑/g
s/&langle;/\⟨/g
s/&lap;/\⪅/g
s/&laquo;/\«/g
s/&larr;/\←/g
s/&larrb;/\⇤/g
s/&larrbfs;/\⤟/g
s/&larrfs;/\⤝/g
s/&larrhk;/\↩/g
s/&larrlp;/\↫/g
s/&larrpl;/\⤹/g
s/&larrsim;/\⥳/g
s/&larrtl;/\↢/g
s/&lat;/\⪫/g
s/&latail;/\⤙/g
s/&late;/\⪭/g
s/&lates;/\⪭︀/g
s/&lbarr;/\⤌/g
s/&lbbrk;/\❲/g
s/&lbrace;/\{/g
s/&lbrack;/\[/g
s/&lbrke;/\⦋/g
s/&lbrksld;/\⦏/g
s/&lbrkslu;/\⦍/g
s/&lcaron;/\ľ/g
s/&lcedil;/\ļ/g
s/&lceil;/\⌈/g
s/&lcub;/\{/g
s/&lcy;/\л/g
s/&ldca;/\⤶/g
s/&ldquo;/\“/g
s/&ldquor;/\„/g
s/&ldrdhar;/\⥧/g
s/&ldrushar;/\⥋/g
s/&ldsh;/\↲/g
s/&le;/\≤/g
s/&leftarrow;/\←/g
s/&leftarrowtail;/\↢/g
s/&leftharpoondown;/\↽/g
s/&leftharpoonup;/\↼/g
s/&leftleftarrows;/\⇇/g
s/&leftrightarrow;/\↔/g
s/&leftrightarrows;/\⇆/g
s/&leftrightharpoons;/\⇋/g
s/&leftrightsquigarrow;/\↭/g
s/&leftthreetimes;/\⋋/g
s/&leg;/\⋚/g
s/&leq;/\≤/g
s/&leqq;/\≦/g
s/&leqslant;/\⩽/g
s/&les;/\⩽/g
s/&lescc;/\⪨/g
s/&lesdot;/\⩿/g
s/&lesdoto;/\⪁/g
s/&lesdotor;/\⪃/g
s/&lesg;/\⋚︀/g
s/&lesges;/\⪓/g
s/&lessapprox;/\⪅/g
s/&lessdot;/\⋖/g
s/&lesseqgtr;/\⋚/g
s/&lesseqqgtr;/\⪋/g
s/&lessgtr;/\≶/g
s/&lesssim;/\≲/g
s/&lfisht;/\⥼/g
s/&lfloor;/\⌊/g
s/&lfr;/\𝔩/g
s/&lg;/\≶/g
s/&lgE;/\⪑/g
s/&lhard;/\↽/g
s/&lharu;/\↼/g
s/&lharul;/\⥪/g
s/&lhblk;/\▄/g
s/&ljcy;/\љ/g
s/&ll;/\≪/g
s/&llarr;/\⇇/g
s/&llcorner;/\⌞/g
s/&llhard;/\⥫/g
s/&lltri;/\◺/g
s/&lmidot;/\ŀ/g
s/&lmoust;/\⎰/g
s/&lmoustache;/\⎰/g
s/&lnE;/\≨/g
s/&lnap;/\⪉/g
s/&lnapprox;/\⪉/g
s/&lne;/\⪇/g
s/&lneq;/\⪇/g
s/&lneqq;/\≨/g
s/&lnsim;/\⋦/g
s/&loang;/\⟬/g
s/&loarr;/\⇽/g
s/&lobrk;/\⟦/g
s/&longleftarrow;/\⟵/g
s/&longleftrightarrow;/\⟷/g
s/&longmapsto;/\⟼/g
s/&longrightarrow;/\⟶/g
s/&looparrowleft;/\↫/g
s/&looparrowright;/\↬/g
s/&lopar;/\⦅/g
s/&lopf;/\𝕝/g
s/&loplus;/\⨭/g
s/&lotimes;/\⨴/g
s/&lowast;/\∗/g
s/&lowbar;/\_/g
s/&loz;/\◊/g
s/&lozenge;/\◊/g
s/&lozf;/\⧫/g
s/&lpar;/\(/g
s/&lparlt;/\⦓/g
s/&lrarr;/\⇆/g
s/&lrcorner;/\⌟/g
s/&lrhar;/\⇋/g
s/&lrhard;/\⥭/g
s/&lrm;/\‎/g
s/&lrtri;/\⊿/g
s/&lsaquo;/\‹/g
s/&lscr;/\𝓁/g
s/&lsh;/\↰/g
s/&lsim;/\≲/g
s/&lsime;/\⪍/g
s/&lsimg;/\⪏/g
s/&lsqb;/\[/g
s/&lsquo;/\‘/g
s/&lsquor;/\‚/g
s/&lstrok;/\ł/g
s/&lt;/\</g
s/&ltcc;/\⪦/g
s/&ltcir;/\⩹/g
s/&ltdot;/\⋖/g
s/&lthree;/\⋋/g
s/&ltimes;/\⋉/g
s/&ltlarr;/\⥶/g
s/&ltquest;/\⩻/g
s/&ltrPar;/\⦖/g
s/&ltri;/\◃/g
s/&ltrie;/\⊴/g
s/&ltrif;/\◂/g
s/&lurdshar;/\⥊/g
s/&luruhar;/\⥦/g
s/&lvertneqq;/\≨︀/g
s/&lvnE;/\≨︀/g
s/&mDDot;/\∺/g
s/&macr;/\¯/g
s/&male;/\♂/g
s/&malt;/\✠/g
s/&maltese;/\✠/g
s/&map;/\↦/g
s/&mapsto;/\↦/g
s/&mapstodown;/\↧/g
s/&mapstoleft;/\↤/g
s/&mapstoup;/\↥/g
s/&marker;/\▮/g
s/&mcomma;/\⨩/g
s/&mcy;/\м/g
s/&mdash;/\—/g
s/&measuredangle;/\∡/g
s/&mfr;/\𝔪/g
s/&mho;/\℧/g
s/&micro;/\µ/g
s/&mid;/\∣/g
s/&midast;/\*/g
s/&midcir;/\⫰/g
s/&middot;/\·/g
s/&minus;/\−/g
s/&minusb;/\⊟/g
s/&minusd;/\∸/g
s/&minusdu;/\⨪/g
s/&mlcp;/\⫛/g
s/&mldr;/\…/g
s/&mnplus;/\∓/g
s/&models;/\⊧/g
s/&mopf;/\𝕞/g
s/&mp;/\∓/g
s/&mscr;/\𝓂/g
s/&mstpos;/\∾/g
s/&mu;/\μ/g
s/&multimap;/\⊸/g
s/&mumap;/\⊸/g
s/&nGg;/\⋙̸/g
s/&nGt;/\≫⃒/g
s/&nGtv;/\≫̸/g
s/&nLeftarrow;/\⇍/g
s/&nLeftrightarrow;/\⇎/g
s/&nLl;/\⋘̸/g
s/&nLt;/\≪⃒/g
s/&nLtv;/\≪̸/g
s/&nRightarrow;/\⇏/g
s/&nVDash;/\⊯/g
s/&nVdash;/\⊮/g
s/&nabla;/\∇/g
s/&nacute;/\ń/g
s/&nang;/\∠⃒/g
s/&nap;/\≉/g
s/&napE;/\⩰̸/g
s/&napid;/\≋̸/g
s/&napos;/\ŉ/g
s/&napprox;/\≉/g
s/&natur;/\♮/g
s/&natural;/\♮/g
s/&naturals;/\ℕ/g
s/&nbsp;/\ /g
s/&nbump;/\≎̸/g
s/&nbumpe;/\≏̸/g
s/&ncap;/\⩃/g
s/&ncaron;/\ň/g
s/&ncedil;/\ņ/g
s/&ncong;/\≇/g
s/&ncongdot;/\⩭̸/g
s/&ncup;/\⩂/g
s/&ncy;/\н/g
s/&ndash;/\–/g
s/&ne;/\≠/g
s/&neArr;/\⇗/g
s/&nearhk;/\⤤/g
s/&nearr;/\↗/g
s/&nearrow;/\↗/g
s/&nedot;/\≐̸/g
s/&nequiv;/\≢/g
s/&nesear;/\⤨/g
s/&nesim;/\≂̸/g
s/&nexist;/\∄/g
s/&nexists;/\∄/g
s/&nfr;/\𝔫/g
s/&ngE;/\≧̸/g
s/&nge;/\≱/g
s/&ngeq;/\≱/g
s/&ngeqq;/\≧̸/g
s/&ngeqslant;/\⩾̸/g
s/&nges;/\⩾̸/g
s/&ngsim;/\≵/g
s/&ngt;/\≯/g
s/&ngtr;/\≯/g
s/&nhArr;/\⇎/g
s/&nharr;/\↮/g
s/&nhpar;/\⫲/g
s/&ni;/\∋/g
s/&nis;/\⋼/g
s/&nisd;/\⋺/g
s/&niv;/\∋/g
s/&njcy;/\њ/g
s/&nlArr;/\⇍/g
s/&nlE;/\≦̸/g
s/&nlarr;/\↚/g
s/&nldr;/\‥/g
s/&nle;/\≰/g
s/&nleftarrow;/\↚/g
s/&nleftrightarrow;/\↮/g
s/&nleq;/\≰/g
s/&nleqq;/\≦̸/g
s/&nleqslant;/\⩽̸/g
s/&nles;/\⩽̸/g
s/&nless;/\≮/g
s/&nlsim;/\≴/g
s/&nlt;/\≮/g
s/&nltri;/\⋪/g
s/&nltrie;/\⋬/g
s/&nmid;/\∤/g
s/&nopf;/\𝕟/g
s/&not;/\¬/g
s/&notin;/\∉/g
s/&notinE;/\⋹̸/g
s/&notindot;/\⋵̸/g
s/&notinva;/\∉/g
s/&notinvb;/\⋷/g
s/&notinvc;/\⋶/g
s/&notni;/\∌/g
s/&notniva;/\∌/g
s/&notnivb;/\⋾/g
s/&notnivc;/\⋽/g
s/&npar;/\∦/g
s/&nparallel;/\∦/g
s/&nparsl;/\⫽⃥/g
s/&npart;/\∂̸/g
s/&npolint;/\⨔/g
s/&npr;/\⊀/g
s/&nprcue;/\⋠/g
s/&npre;/\⪯̸/g
s/&nprec;/\⊀/g
s/&npreceq;/\⪯̸/g
s/&nrArr;/\⇏/g
s/&nrarr;/\↛/g
s/&nrarrc;/\⤳̸/g
s/&nrarrw;/\↝̸/g
s/&nrightarrow;/\↛/g
s/&nrtri;/\⋫/g
s/&nrtrie;/\⋭/g
s/&nsc;/\⊁/g
s/&nsccue;/\⋡/g
s/&nsce;/\⪰̸/g
s/&nscr;/\𝓃/g
s/&nshortmid;/\∤/g
s/&nshortparallel;/\∦/g
s/&nsim;/\≁/g
s/&nsime;/\≄/g
s/&nsimeq;/\≄/g
s/&nsmid;/\∤/g
s/&nspar;/\∦/g
s/&nsqsube;/\⋢/g
s/&nsqsupe;/\⋣/g
s/&nsub;/\⊄/g
s/&nsubE;/\⫅̸/g
s/&nsube;/\⊈/g
s/&nsubset;/\⊂⃒/g
s/&nsubseteq;/\⊈/g
s/&nsubseteqq;/\⫅̸/g
s/&nsucc;/\⊁/g
s/&nsucceq;/\⪰̸/g
s/&nsup;/\⊅/g
s/&nsupE;/\⫆̸/g
s/&nsupe;/\⊉/g
s/&nsupset;/\⊃⃒/g
s/&nsupseteq;/\⊉/g
s/&nsupseteqq;/\⫆̸/g
s/&ntgl;/\≹/g
s/&ntilde;/\ñ/g
s/&ntlg;/\≸/g
s/&ntriangleleft;/\⋪/g
s/&ntrianglelefteq;/\⋬/g
s/&ntriangleright;/\⋫/g
s/&ntrianglerighteq;/\⋭/g
s/&nu;/\ν/g
s/&num;/\#/g
s/&numero;/\№/g
s/&numsp;/\ /g
s/&nvDash;/\⊭/g
s/&nvHarr;/\⤄/g
s/&nvap;/\≍⃒/g
s/&nvdash;/\⊬/g
s/&nvge;/\≥⃒/g
s/&nvgt;/\>⃒/g
s/&nvinfin;/\⧞/g
s/&nvlArr;/\⤂/g
s/&nvle;/\≤⃒/g
s/&nvlt;/\<⃒/g
s/&nvltrie;/\⊴⃒/g
s/&nvrArr;/\⤃/g
s/&nvrtrie;/\⊵⃒/g
s/&nvsim;/\∼⃒/g
s/&nwArr;/\⇖/g
s/&nwarhk;/\⤣/g
s/&nwarr;/\↖/g
s/&nwarrow;/\↖/g
s/&nwnear;/\⤧/g
s/&oS;/\Ⓢ/g
s/&oacute;/\ó/g
s/&oast;/\⊛/g
s/&ocir;/\⊚/g
s/&ocirc;/\ô/g
s/&ocy;/\о/g
s/&odash;/\⊝/g
s/&odblac;/\ő/g
s/&odiv;/\⨸/g
s/&odot;/\⊙/g
s/&odsold;/\⦼/g
s/&oelig;/\œ/g
s/&ofcir;/\⦿/g
s/&ofr;/\𝔬/g
s/&ogon;/\˛/g
s/&ograve;/\ò/g
s/&ogt;/\⧁/g
s/&ohbar;/\⦵/g
s/&ohm;/\Ω/g
s/&oint;/\∮/g
s/&olarr;/\↺/g
s/&olcir;/\⦾/g
s/&olcross;/\⦻/g
s/&oline;/\‾/g
s/&olt;/\⧀/g
s/&omacr;/\ō/g
s/&omega;/\ω/g
s/&omicron;/\ο/g
s/&omid;/\⦶/g
s/&ominus;/\⊖/g
s/&oopf;/\𝕠/g
s/&opar;/\⦷/g
s/&operp;/\⦹/g
s/&oplus;/\⊕/g
s/&or;/\∨/g
s/&orarr;/\↻/g
s/&ord;/\⩝/g
s/&order;/\ℴ/g
s/&orderof;/\ℴ/g
s/&ordf;/\ª/g
s/&ordm;/\º/g
s/&origof;/\⊶/g
s/&oror;/\⩖/g
s/&orslope;/\⩗/g
s/&orv;/\⩛/g
s/&oscr;/\ℴ/g
s/&oslash;/\ø/g
s/&osol;/\⊘/g
s/&otilde;/\õ/g
s/&otimes;/\⊗/g
s/&otimesas;/\⨶/g
s/&ouml;/\ö/g
s/&ovbar;/\⌽/g
s/&par;/\∥/g
s/&para;/\¶/g
s/&parallel;/\∥/g
s/&parsim;/\⫳/g
s/&parsl;/\⫽/g
s/&part;/\∂/g
s/&pcy;/\п/g
s/&percnt;/\%/g
s/&period;/\./g
s/&permil;/\‰/g
s/&perp;/\⊥/g
s/&pertenk;/\‱/g
s/&pfr;/\𝔭/g
s/&phi;/\φ/g
s/&phiv;/\ϕ/g
s/&phmmat;/\ℳ/g
s/&phone;/\☎/g
s/&pi;/\π/g
s/&pitchfork;/\⋔/g
s/&piv;/\ϖ/g
s/&planck;/\ℏ/g
s/&planckh;/\ℎ/g
s/&plankv;/\ℏ/g
s/&plus;/\+/g
s/&plusacir;/\⨣/g
s/&plusb;/\⊞/g
s/&pluscir;/\⨢/g
s/&plusdo;/\∔/g
s/&plusdu;/\⨥/g
s/&pluse;/\⩲/g
s/&plusmn;/\±/g
s/&plussim;/\⨦/g
s/&plustwo;/\⨧/g
s/&pm;/\±/g
s/&pointint;/\⨕/g
s/&popf;/\𝕡/g
s/&pound;/\£/g
s/&pr;/\≺/g
s/&prE;/\⪳/g
s/&prap;/\⪷/g
s/&prcue;/\≼/g
s/&pre;/\⪯/g
s/&prec;/\≺/g
s/&precapprox;/\⪷/g
s/&preccurlyeq;/\≼/g
s/&preceq;/\⪯/g
s/&precnapprox;/\⪹/g
s/&precneqq;/\⪵/g
s/&precnsim;/\⋨/g
s/&precsim;/\≾/g
s/&prime;/\′/g
s/&primes;/\ℙ/g
s/&prnE;/\⪵/g
s/&prnap;/\⪹/g
s/&prnsim;/\⋨/g
s/&prod;/\∏/g
s/&profalar;/\⌮/g
s/&profline;/\⌒/g
s/&profsurf;/\⌓/g
s/&prop;/\∝/g
s/&propto;/\∝/g
s/&prsim;/\≾/g
s/&prurel;/\⊰/g
s/&pscr;/\𝓅/g
s/&psi;/\ψ/g
s/&puncsp;/\ /g
s/&qfr;/\𝔮/g
s/&qint;/\⨌/g
s/&qopf;/\𝕢/g
s/&qprime;/\⁗/g
s/&qscr;/\𝓆/g
s/&quaternions;/\ℍ/g
s/&quatint;/\⨖/g
s/&quest;/\?/g
s/&questeq;/\≟/g
s/&quot;/\"/g
s/&rAarr;/\⇛/g
s/&rArr;/\⇒/g
s/&rAtail;/\⤜/g
s/&rBarr;/\⤏/g
s/&rHar;/\⥤/g
s/&race;/\∽̱/g
s/&racute;/\ŕ/g
s/&radic;/\√/g
s/&raemptyv;/\⦳/g
s/&rang;/\⟩/g
s/&rangd;/\⦒/g
s/&range;/\⦥/g
s/&rangle;/\⟩/g
s/&raquo;/\»/g
s/&rarr;/\→/g
s/&rarrap;/\⥵/g
s/&rarrb;/\⇥/g
s/&rarrbfs;/\⤠/g
s/&rarrc;/\⤳/g
s/&rarrfs;/\⤞/g
s/&rarrhk;/\↪/g
s/&rarrlp;/\↬/g
s/&rarrpl;/\⥅/g
s/&rarrsim;/\⥴/g
s/&rarrtl;/\↣/g
s/&rarrw;/\↝/g
s/&ratail;/\⤚/g
s/&ratio;/\∶/g
s/&rationals;/\ℚ/g
s/&rbarr;/\⤍/g
s/&rbbrk;/\❳/g
s/&rbrace;/\}/g
s/&rbrack;/\]/g
s/&rbrke;/\⦌/g
s/&rbrksld;/\⦎/g
s/&rbrkslu;/\⦐/g
s/&rcaron;/\ř/g
s/&rcedil;/\ŗ/g
s/&rceil;/\⌉/g
s/&rcub;/\}/g
s/&rcy;/\р/g
s/&rdca;/\⤷/g
s/&rdldhar;/\⥩/g
s/&rdquo;/\”/g
s/&rdquor;/\”/g
s/&rdsh;/\↳/g
s/&real;/\ℜ/g
s/&realine;/\ℛ/g
s/&realpart;/\ℜ/g
s/&reals;/\ℝ/g
s/&rect;/\▭/g
s/&reg;/\®/g
s/&rfisht;/\⥽/g
s/&rfloor;/\⌋/g
s/&rfr;/\𝔯/g
s/&rhard;/\⇁/g
s/&rharu;/\⇀/g
s/&rharul;/\⥬/g
s/&rho;/\ρ/g
s/&rhov;/\ϱ/g
s/&rightarrow;/\→/g
s/&rightarrowtail;/\↣/g
s/&rightharpoondown;/\⇁/g
s/&rightharpoonup;/\⇀/g
s/&rightleftarrows;/\⇄/g
s/&rightleftharpoons;/\⇌/g
s/&rightrightarrows;/\⇉/g
s/&rightsquigarrow;/\↝/g
s/&rightthreetimes;/\⋌/g
s/&ring;/\˚/g
s/&risingdotseq;/\≓/g
s/&rlarr;/\⇄/g
s/&rlhar;/\⇌/g
s/&rlm;/\‏/g
s/&rmoust;/\⎱/g
s/&rmoustache;/\⎱/g
s/&rnmid;/\⫮/g
s/&roang;/\⟭/g
s/&roarr;/\⇾/g
s/&robrk;/\⟧/g
s/&ropar;/\⦆/g
s/&ropf;/\𝕣/g
s/&roplus;/\⨮/g
s/&rotimes;/\⨵/g
s/&rpar;/\)/g
s/&rpargt;/\⦔/g
s/&rppolint;/\⨒/g
s/&rrarr;/\⇉/g
s/&rsaquo;/\›/g
s/&rscr;/\𝓇/g
s/&rsh;/\↱/g
s/&rsqb;/\]/g
s/&rsquo;/\’/g
s/&rsquor;/\’/g
s/&rthree;/\⋌/g
s/&rtimes;/\⋊/g
s/&rtri;/\▹/g
s/&rtrie;/\⊵/g
s/&rtrif;/\▸/g
s/&rtriltri;/\⧎/g
s/&ruluhar;/\⥨/g
s/&rx;/\℞/g
s/&sacute;/\ś/g
s/&sbquo;/\‚/g
s/&sc;/\≻/g
s/&scE;/\⪴/g
s/&scap;/\⪸/g
s/&scaron;/\š/g
s/&sccue;/\≽/g
s/&sce;/\⪰/g
s/&scedil;/\ş/g
s/&scirc;/\ŝ/g
s/&scnE;/\⪶/g
s/&scnap;/\⪺/g
s/&scnsim;/\⋩/g
s/&scpolint;/\⨓/g
s/&scsim;/\≿/g
s/&scy;/\с/g
s/&sdot;/\⋅/g
s/&sdotb;/\⊡/g
s/&sdote;/\⩦/g
s/&seArr;/\⇘/g
s/&searhk;/\⤥/g
s/&searr;/\↘/g
s/&searrow;/\↘/g
s/&sect;/\§/g
s/&semi;/\;/g
s/&seswar;/\⤩/g
s/&setminus;/\∖/g
s/&setmn;/\∖/g
s/&sext;/\✶/g
s/&sfr;/\𝔰/g
s/&sfrown;/\⌢/g
s/&sharp;/\♯/g
s/&shchcy;/\щ/g
s/&shcy;/\ш/g
s/&shortmid;/\∣/g
s/&shortparallel;/\∥/g
s/&shy;/\­/g
s/&sigma;/\σ/g
s/&sigmaf;/\ς/g
s/&sigmav;/\ς/g
s/&sim;/\∼/g
s/&simdot;/\⩪/g
s/&sime;/\≃/g
s/&simeq;/\≃/g
s/&simg;/\⪞/g
s/&simgE;/\⪠/g
s/&siml;/\⪝/g
s/&simlE;/\⪟/g
s/&simne;/\≆/g
s/&simplus;/\⨤/g
s/&simrarr;/\⥲/g
s/&slarr;/\←/g
s/&smallsetminus;/\∖/g
s/&smashp;/\⨳/g
s/&smeparsl;/\⧤/g
s/&smid;/\∣/g
s/&smile;/\⌣/g
s/&smt;/\⪪/g
s/&smte;/\⪬/g
s/&smtes;/\⪬︀/g
s/&softcy;/\ь/g
s/&sol;/\\/
s/&solb;/\⧄/g
s/&solbar;/\⌿/g
s/&sopf;/\𝕤/g
s/&spades;/\♠/g
s/&spadesuit;/\♠/g
s/&spar;/\∥/g
s/&sqcap;/\⊓/g
s/&sqcaps;/\⊓︀/g
s/&sqcup;/\⊔/g
s/&sqcups;/\⊔︀/g
s/&sqsub;/\⊏/g
s/&sqsube;/\⊑/g
s/&sqsubset;/\⊏/g
s/&sqsubseteq;/\⊑/g
s/&sqsup;/\⊐/g
s/&sqsupe;/\⊒/g
s/&sqsupset;/\⊐/g
s/&sqsupseteq;/\⊒/g
s/&squ;/\□/g
s/&square;/\□/g
s/&squarf;/\▪/g
s/&squf;/\▪/g
s/&srarr;/\→/g
s/&sscr;/\𝓈/g
s/&ssetmn;/\∖/g
s/&ssmile;/\⌣/g
s/&sstarf;/\⋆/g
s/&star;/\☆/g
s/&starf;/\★/g
s/&straightepsilon;/\ϵ/g
s/&straightphi;/\ϕ/g
s/&strns;/\¯/g
s/&sub;/\⊂/g
s/&subE;/\⫅/g
s/&subdot;/\⪽/g
s/&sube;/\⊆/g
s/&subedot;/\⫃/g
s/&submult;/\⫁/g
s/&subnE;/\⫋/g
s/&subne;/\⊊/g
s/&subplus;/\⪿/g
s/&subrarr;/\⥹/g
s/&subset;/\⊂/g
s/&subseteq;/\⊆/g
s/&subseteqq;/\⫅/g
s/&subsetneq;/\⊊/g
s/&subsetneqq;/\⫋/g
s/&subsim;/\⫇/g
s/&subsub;/\⫕/g
s/&subsup;/\⫓/g
s/&succ;/\≻/g
s/&succapprox;/\⪸/g
s/&succcurlyeq;/\≽/g
s/&succeq;/\⪰/g
s/&succnapprox;/\⪺/g
s/&succneqq;/\⪶/g
s/&succnsim;/\⋩/g
s/&succsim;/\≿/g
s/&sum;/\∑/g
s/&sung;/\♪/g
s/&sup1;/\¹/g
s/&sup2;/\²/g
s/&sup3;/\³/g
s/&sup;/\⊃/g
s/&supE;/\⫆/g
s/&supdot;/\⪾/g
s/&supdsub;/\⫘/g
s/&supe;/\⊇/g
s/&supedot;/\⫄/g
s/&suphsol;/\⟉/g
s/&suphsub;/\⫗/g
s/&suplarr;/\⥻/g
s/&supmult;/\⫂/g
s/&supnE;/\⫌/g
s/&supne;/\⊋/g
s/&supplus;/\⫀/g
s/&supset;/\⊃/g
s/&supseteq;/\⊇/g
s/&supseteqq;/\⫆/g
s/&supsetneq;/\⊋/g
s/&supsetneqq;/\⫌/g
s/&supsim;/\⫈/g
s/&supsub;/\⫔/g
s/&supsup;/\⫖/g
s/&swArr;/\⇙/g
s/&swarhk;/\⤦/g
s/&swarr;/\↙/g
s/&swarrow;/\↙/g
s/&swnwar;/\⤪/g
s/&szlig;/\ß/g
s/&target;/\⌖/g
s/&tau;/\τ/g
s/&tbrk;/\⎴/g
s/&tcaron;/\ť/g
s/&tcedil;/\ţ/g
s/&tcy;/\т/g
s/&tdot;/\⃛/g
s/&telrec;/\⌕/g
s/&tfr;/\𝔱/g
s/&there4;/\∴/g
s/&therefore;/\∴/g
s/&theta;/\θ/g
s/&thetasym;/\ϑ/g
s/&thetav;/\ϑ/g
s/&thickapprox;/\≈/g
s/&thicksim;/\∼/g
s/&thinsp;/\ /g
s/&thkap;/\≈/g
s/&thksim;/\∼/g
s/&thorn;/\þ/g
s/&tilde;/\˜/g
s/&times;/\×/g
s/&timesb;/\⊠/g
s/&timesbar;/\⨱/g
s/&timesd;/\⨰/g
s/&tint;/\∭/g
s/&toea;/\⤨/g
s/&top;/\⊤/g
s/&topbot;/\⌶/g
s/&topcir;/\⫱/g
s/&topf;/\𝕥/g
s/&topfork;/\⫚/g
s/&tosa;/\⤩/g
s/&tprime;/\‴/g
s/&trade;/\™/g
s/&triangle;/\▵/g
s/&triangledown;/\▿/g
s/&triangleleft;/\◃/g
s/&trianglelefteq;/\⊴/g
s/&triangleq;/\≜/g
s/&triangleright;/\▹/g
s/&trianglerighteq;/\⊵/g
s/&tridot;/\◬/g
s/&trie;/\≜/g
s/&triminus;/\⨺/g
s/&triplus;/\⨹/g
s/&trisb;/\⧍/g
s/&tritime;/\⨻/g
s/&trpezium;/\⏢/g
s/&tscr;/\𝓉/g
s/&tscy;/\ц/g
s/&tshcy;/\ћ/g
s/&tstrok;/\ŧ/g
s/&twixt;/\≬/g
s/&twoheadleftarrow;/\↞/g
s/&twoheadrightarrow;/\↠/g
s/&uArr;/\⇑/g
s/&uHar;/\⥣/g
s/&uacute;/\ú/g
s/&uarr;/\↑/g
s/&ubrcy;/\ў/g
s/&ubreve;/\ŭ/g
s/&ucirc;/\û/g
s/&ucy;/\у/g
s/&udarr;/\⇅/g
s/&udblac;/\ű/g
s/&udhar;/\⥮/g
s/&ufisht;/\⥾/g
s/&ufr;/\𝔲/g
s/&ugrave;/\ù/g
s/&uharl;/\↿/g
s/&uharr;/\↾/g
s/&uhblk;/\▀/g
s/&ulcorn;/\⌜/g
s/&ulcorner;/\⌜/g
s/&ulcrop;/\⌏/g
s/&ultri;/\◸/g
s/&umacr;/\ū/g
s/&uml;/\¨/g
s/&uogon;/\ų/g
s/&uopf;/\𝕦/g
s/&uparrow;/\↑/g
s/&updownarrow;/\↕/g
s/&upharpoonleft;/\↿/g
s/&upharpoonright;/\↾/g
s/&uplus;/\⊎/g
s/&upsi;/\υ/g
s/&upsih;/\ϒ/g
s/&upsilon;/\υ/g
s/&upuparrows;/\⇈/g
s/&urcorn;/\⌝/g
s/&urcorner;/\⌝/g
s/&urcrop;/\⌎/g
s/&uring;/\ů/g
s/&urtri;/\◹/g
s/&uscr;/\𝓊/g
s/&utdot;/\⋰/g
s/&utilde;/\ũ/g
s/&utri;/\▵/g
s/&utrif;/\▴/g
s/&uuarr;/\⇈/g
s/&uuml;/\ü/g
s/&uwangle;/\⦧/g
s/&vArr;/\⇕/g
s/&vBar;/\⫨/g
s/&vBarv;/\⫩/g
s/&vDash;/\⊨/g
s/&vangrt;/\⦜/g
s/&varepsilon;/\ϵ/g
s/&varkappa;/\ϰ/g
s/&varnothing;/\∅/g
s/&varphi;/\ϕ/g
s/&varpi;/\ϖ/g
s/&varpropto;/\∝/g
s/&varr;/\↕/g
s/&varrho;/\ϱ/g
s/&varsigma;/\ς/g
s/&varsubsetneq;/\⊊︀/g
s/&varsubsetneqq;/\⫋︀/g
s/&varsupsetneq;/\⊋︀/g
s/&varsupsetneqq;/\⫌︀/g
s/&vartheta;/\ϑ/g
s/&vartriangleleft;/\⊲/g
s/&vartriangleright;/\⊳/g
s/&vcy;/\в/g
s/&vdash;/\⊢/g
s/&vee;/\∨/g
s/&veebar;/\⊻/g
s/&veeeq;/\≚/g
s/&vellip;/\⋮/g
s/&verbar;/\|/g
s/&vert;/\|/g
s/&vfr;/\𝔳/g
s/&vltri;/\⊲/g
s/&vnsub;/\⊂⃒/g
s/&vnsup;/\⊃⃒/g
s/&vopf;/\𝕧/g
s/&vprop;/\∝/g
s/&vrtri;/\⊳/g
s/&vscr;/\𝓋/g
s/&vsubnE;/\⫋︀/g
s/&vsubne;/\⊊︀/g
s/&vsupnE;/\⫌︀/g
s/&vsupne;/\⊋︀/g
s/&vzigzag;/\⦚/g
s/&wcirc;/\ŵ/g
s/&wedbar;/\⩟/g
s/&wedge;/\∧/g
s/&wedgeq;/\≙/g
s/&weierp;/\℘/g
s/&wfr;/\𝔴/g
s/&wopf;/\𝕨/g
s/&wp;/\℘/g
s/&wr;/\≀/g
s/&wreath;/\≀/g
s/&wscr;/\𝓌/g
s/&xcap;/\⋂/g
s/&xcirc;/\◯/g
s/&xcup;/\⋃/g
s/&xdtri;/\▽/g
s/&xfr;/\𝔵/g
s/&xhArr;/\⟺/g
s/&xharr;/\⟷/g
s/&xi;/\ξ/g
s/&xlArr;/\⟸/g
s/&xlarr;/\⟵/g
s/&xmap;/\⟼/g
s/&xnis;/\⋻/g
s/&xodot;/\⨀/g
s/&xopf;/\𝕩/g
s/&xoplus;/\⨁/g
s/&xotime;/\⨂/g
s/&xrArr;/\⟹/g
s/&xrarr;/\⟶/g
s/&xscr;/\𝓍/g
s/&xsqcup;/\⨆/g
s/&xuplus;/\⨄/g
s/&xutri;/\△/g
s/&xvee;/\⋁/g
s/&xwedge;/\⋀/g
s/&yacute;/\ý/g
s/&yacy;/\я/g
s/&ycirc;/\ŷ/g
s/&ycy;/\ы/g
s/&yen;/\¥/g
s/&yfr;/\𝔶/g
s/&yicy;/\ї/g
s/&yopf;/\𝕪/g
s/&yscr;/\𝓎/g
s/&yucy;/\ю/g
s/&yuml;/\ÿ/g
s/&zacute;/\ź/g
s/&zcaron;/\ž/g
s/&zcy;/\з/g
s/&zdot;/\ż/g
s/&zeetrf;/\ℨ/g
s/&zeta;/\ζ/g
s/&zfr;/\𝔷/g
s/&zhcy;/\ж/g
s/&zigrarr;/\⇝/g
s/&zopf;/\𝕫/g
s/&zscr;/\𝓏/g
s/&zwj;/\‍/g
s/&zwnj;/\‌/g
s/&AElig/\Æ/g
s/&AMP/\&/g
s/&Aacute/\Á/g
s/&Acirc/\Â/g
s/&Agrave/\À/g
s/&Aring/\Å/g
s/&Atilde/\Ã/g
s/&Auml/\Ä/g
s/&COPY/\©/g
s/&Ccedil/\Ç/g
s/&ETH/\Ð/g
s/&Eacute/\É/g
s/&Ecirc/\Ê/g
s/&Egrave/\È/g
s/&Euml/\Ë/g
s/&GT/\>/g
s/&Iacute/\Í/g
s/&Icirc/\Î/g
s/&Igrave/\Ì/g
s/&Iuml/\Ï/g
s/&LT/\</g
s/&Ntilde/\Ñ/g
s/&Oacute/\Ó/g
s/&Ocirc/\Ô/g
s/&Ograve/\Ò/g
s/&Oslash/\Ø/g
s/&Otilde/\Õ/g
s/&Ouml/\Ö/g
s/&QUOT/\"/g
s/&REG/\®/g
s/&THORN/\Þ/g
s/&Uacute/\Ú/g
s/&Ucirc/\Û/g
s/&Ugrave/\Ù/g
s/&Uuml/\Ü/g
s/&Yacute/\Ý/g
s/&aacute/\á/g
s/&acirc/\â/g
s/&acute/\´/g
s/&aelig/\æ/g
s/&agrave/\à/g
s/&amp/\&/g
s/&aring/\å/g
s/&atilde/\ã/g
s/&auml/\ä/g
s/&brvbar/\¦/g
s/&ccedil/\ç/g
s/&cedil/\¸/g
s/&cent/\¢/g
s/&copy/\©/g
s/&curren/\¤/g
s/&deg/\°/g
s/&divide/\÷/g
s/&eacute/\é/g
s/&ecirc/\ê/g
s/&egrave/\è/g
s/&eth/\ð/g
s/&euml/\ë/g
s/&frac12/\½/g
s/&frac14/\¼/g
s/&frac34/\¾/g
s/&gt/\>/g
s/&iacute/\í/g
s/&icirc/\î/g
s/&iexcl/\¡/g
s/&igrave/\ì/g
s/&iquest/\¿/g
s/&iuml/\ï/g
s/&laquo/\«/g
s/&lt/\</g
s/&macr/\¯/g
s/&micro/\µ/g
s/&middot/\·/g
s/&nbsp/\ /g
s/&not/\¬/g
s/&ntilde/\ñ/g
s/&oacute/\ó/g
s/&ocirc/\ô/g
s/&ograve/\ò/g
s/&ordf/\ª/g
s/&ordm/\º/g
s/&oslash/\ø/g
s/&otilde/\õ/g
s/&ouml/\ö/g
s/&para/\¶/g
s/&plusmn/\±/g
s/&pound/\£/g
s/&quot/\"/g
s/&raquo/\»/g
s/&reg/\®/g
s/&sect/\§/g
s/&shy/\­/g
s/&sup1/\¹/g
s/&sup2/\²/g
s/&sup3/\³/g
s/&szlig/\ß/g
s/&thorn/\þ/g
s/&times/\×/g
s/&uacute/\ú/g
s/&ucirc/\û/g
s/&ugrave/\ù/g
s/&uml/\¨/g
s/&uuml/\ü/g
s/&yacute/\ý/g
s/&yen/\¥/g
s/&yuml/\ÿ/g
